# Generated by Django 5.1.6 on 2025-02-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_business_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
    ]
