# Generated by Django 5.1.6 on 2025-02-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_business_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
    ]
