# Generated by Django 5.1.6 on 2025-02-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AddField(
            model_name='business',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='business_videos/'),
        ),
    ]
