# Generated by Django 5.1.6 on 2025-02-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_business_image_business_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='signature_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_for_business', to='main.product'),
        ),
    ]
