# Generated by Django 5.1.6 on 2025-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='main.product'),
        ),
    ]
